### PR TITLE
need to check the type of the SliceElement not the Slice itself

### PR DESCRIPTION
**Pull request by UplinkCoder**
you need to check the type of the SliceElement. not the Slice itself

### CODE REVIEW

**Comment by deadalnix** [comment]
1/ Use descriptive title.
2/ Add a test we we can ensure that there is no regression.

**Comment by schancel** [comment]
https://github.com/blog/1943-how-to-write-the-perfect-pull-request

**Comment by schancel** [comment]
If I look at git blame and look at this commit message, it will tell me absolutely nothing about why the change was made.

**Comment by UplinkCoder** [comment]
updated git comment

**Comment by UplinkCoder** [comment]
@deadalnix providing a test for this is going to be difficult since mainline does not support CT string-manipulation yet

**Comment by deadalnix** [comment]
Either it is dead code, and in which case this do not qualify as an IMPORTANT FIX, or it is not dead code and a test can be written.

Every single time I have to argue the same thing. If you make a bug report, at least put an error message and if appropriate a stack trace. If you write some code, add a test. It is clear that arguing has failed, so I'm gonna stop and close.

**Comment by UplinkCoder** [comment]
There you go : 
```
string CTString(string s) {
  return s;
}

void main() {
  enum str = CTString("hello");
  return 0;
}
```

**Comment by UplinkCoder** [comment]
this leads to
core.exception.AssertError@libd-llvm/libd/src/d/ir/type.d(156): Assertion failure

**Comment by UplinkCoder** [comment]
@deadalnix  reopen the PR.

**Comment by deadalnix** [comment]
Cool, now please have a descriptive title so someone looking in the logs can understand what this change is about and this gets in.

**Comment by UplinkCoder** [comment]
This bug was pretty hard to track down because the assertion is triggered nowhere near the source of the error.

**Comment by UplinkCoder** [comment]
@deadalnix reopen and merge please.

**Comment by deadalnix** [comment]
There is still no PR for the test that exercise that code.

**Comment by UplinkCoder** [comment]
There you go
https://github.com/deadalnix/SDC/pull/92

**Pull request merged**
